server:
  port: 8761

spring:
  application:
    name: funbank-service-registry

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Funbank Service Registry
    description: Eureka Service Registry for Funbank banking system
    version: 1.0.0

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    com.funbank: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"