server:
  port: 9090

spring:
  application:
    name: funbank-api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Default to dev profile
  config:
    import: "optional:configserver:http://funbank-config:funbank-config-2024@localhost:8888/config/"
  
  # Redis configuration for rate limiting
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:password}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenish-rate: 10
            redis-rate-limiter.burst-capacity: 20
            redis-rate-limiter.requested-tokens: 1
            key-resolver: "#{@userKeyResolver}"
      discovery:
        locator:
          enabled: false  # Using programmatic routes instead
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}"
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

eureka:
  client:
    enabled: false  # Disabled by default, enabled in production
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Funbank JWT Configuration
funbank:
  jwt:
    secret: ${JWT_SECRET:}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}  # 1 hour
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}  # 7 days
    issuer: ${JWT_ISSUER:funbank}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true

info:
  app:
    name: Funbank API Gateway
    description: Spring Cloud Gateway for Funbank banking system with integrated security
    version: 1.0.0

logging:
  level:
    com.funbank: INFO
    com.funbank.gateway.filter: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
