server:
  port: 9091

spring:
  application:
    name: funbank-user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:http://funbank-config:funbank-config-2024@localhost:8888/config/"
  
  # Database configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/funbank_users?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:funbank_user}
    password: ${DB_PASSWORD:funbank_pass_2024}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # Redis configuration for caching
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:password}
      timeout: 2000ms

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

# JWT Configuration
funbank:
  jwt:
    secret: ${JWT_SECRET:}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

info:
  app:
    name: Funbank User Service
    description: User management microservice for Funbank banking system
    version: 1.0.0

logging:
  level:
    com.funbank: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"